version: "3"
services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATA_DIR: /data/db
    volumes:
      - ./db/fixtures/:/fixtures
      - ./db/initdb.d/:/docker-entrypoint-initdb.d
      - mongodb:/data
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  nodejs:
    build: .
    environment:
      - NODE_ENV=development
    command: /bin/sh -c "npm run build-ts && npm run start"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
volumes:
  nodejs:
    driver: local
  mongodb: ~
